// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH5wNRMMrvNdUsgivT7yQuGcrEWALI7uY',
    appId: '1:165226918727:web:4af563f91472e472fb9262',
    messagingSenderId: '165226918727',
    projectId: 'sample-8389d',
    authDomain: 'sample-8389d.firebaseapp.com',
    storageBucket: 'sample-8389d.appspot.com',
    measurementId: 'G-6GT4RQLHWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRKS_cZSq_YIiZiWQsifLc9LRZ6tqkzkA',
    appId: '1:165226918727:android:36032eae7f7b7ba3fb9262',
    messagingSenderId: '165226918727',
    projectId: 'sample-8389d',
    storageBucket: 'sample-8389d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6RDgzuX_GudNHaOWsqFD69lrnQn4wm3E',
    appId: '1:165226918727:ios:84809ca6eb550ac8fb9262',
    messagingSenderId: '165226918727',
    projectId: 'sample-8389d',
    storageBucket: 'sample-8389d.appspot.com',
    iosClientId: '165226918727-o7srtqspj9lp9b3kl4kac9rr7dtglqkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.showmedeadline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6RDgzuX_GudNHaOWsqFD69lrnQn4wm3E',
    appId: '1:165226918727:ios:03b7228098495c6bfb9262',
    messagingSenderId: '165226918727',
    projectId: 'sample-8389d',
    storageBucket: 'sample-8389d.appspot.com',
    iosClientId: '165226918727-ejp8ql5hfaqnk2dqo9ro2e6gli20nfkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.showmedeadline.RunnerTests',
  );
}
